[scan_dir]
scan_dir = "$HOME/Downloads/"

[rules.Images]
target_path = "$HOME/Downloads/Images"
extensions = [".jpg", ".png", ".gif"]

[rules.Documents]
target_path = "$HOME/Downloads/Documents"
extensions = [".pdf", ".docx", ".txt"]

[logger]
max_size = 10
max_age = 28
max_backups = 4
compress = true