scan_dir = "$HOME/Downloads/"
scan_dirs = ["$HOME/Downloads/", "$HOME/Downloads/Sorting"]
logs_dir = "./logs"

[rules.Images]
target_dir = "Images"
extensions = [".jpg", ".png", ".gif"]

[rules.Documents]
target_dir = "Documents"
extensions = [".pdf", ".docx", ".txt"]

[rules.Archives]
target_dir = "Archives"
extensions = [".tar.gz"]

[logger]
max_size = 10
max_age = 28
max_backups = 4
compress = true
